/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-104288-g9b17273c77-20211009"
#endif /* AVUTIL_FFVERSION_H */
